source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# Specify your gem's dependencies in Top-Movies-CLI.gemspec
gemspec
gem 'pry'
gem 'nokogiri', '1.8.2'
#gem 'rspec'
